apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: inline-sample-api
  title: インラインサンプル API
  description: デモ用の簡易 API。OpenAPI 定義をこの YAML に直接記述。
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/rhdh-team-2
  definition: |
    openapi: 3.0.3
    info:
      title: Inline Sample API
      version: 1.0.0
      description: >
        Backstage に直接表示させる最小構成の OpenAPI 定義。
    paths:
      /hello:
        get:
          summary: Hello endpoint
          operationId: getHello
          responses:
            '200':
              description: Returns a greeting
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Hello, world!
